{
  "hash": "09d2d8217c0550df62bee0926cff59d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verify the Claim: Poverty Change in Philadelphia\"\nauthor: \"Terry Xu\"\ndate: 2026-09-24\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n## Article\n\n[New Census figures on Philly neighborhoods show inequality, high numbers of whites living in poverty](https://whyy.org/articles/new-census-figures-on-philly-neighborhoods-show-inequality-high-numbers-of-whites-living-in-poverty/)\n\n## Part 1: Reconstructing the Article's Data\n\nThe article compares Philadelphia neighborhood poverty using the 2006–2010 and\n2013–2017 ACS 5-year estimates. I use `survey = \"acs5\"` with `year = 2010` and\n`year = 2017` to retrieve those periods. The periods do not overlap, so they\ndo not share collection years. For the change test, I use the standard\napproximation that the estimates from the two periods are independent.\n\nI use table B17001: `B17001_002` counts people below the poverty level, and\n`B17001_001` counts people for whom poverty status is determined. Dividing\nthese gives the poverty rate. I assume this measure corresponds to the\narticle's overall poverty measure. Because its neighborhood-to-tract definitions\nare unavailable, I compare Philadelphia census tracts rather than reconstructing\nits neighborhood totals. I match tracts by GEOID and assume matched tracts\nrepresent comparable areas; matching identifiers alone does not verify unchanged\nboundaries.\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_10 <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = c(\n    poor = \"B17001_002\",\n    poverty_universe = \"B17001_001\"\n  ),\n  year = 2010,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\npoverty_17 <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = c(\n    poor = \"B17001_002\",\n    poverty_universe = \"B17001_001\"\n  ),\n  year = 2017,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\ndim(poverty_10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 384   6\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(poverty_17)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 384   6\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_10 <- poverty_10 %>%\n  select(\n    GEOID,\n    poor_10E = poorE,\n    poor_10M = poorM,\n    universe_10E = poverty_universeE,\n    universe_10M = poverty_universeM\n  )\n\npoverty_17 <- poverty_17 %>%\n  select(\n    GEOID,\n    NAME,\n    poor_17E = poorE,\n    poor_17M = poorM,\n    universe_17E = poverty_universeE,\n    universe_17M = poverty_universeM\n  )\n\npoverty <- poverty_17 %>%\n  left_join(poverty_10, by = \"GEOID\")\n\npoverty %>%\n  summarize(\n    n_tracts = n(),\n    no_2010_match = sum(is.na(poor_10E))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  n_tracts no_2010_match\n     <int>         <int>\n1      384             0\n```\n\n\n:::\n:::\n\n\n## Part 2: Testing Poverty Change\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty <- poverty %>%\n  mutate(\n    poverty_rate_10 = poor_10E / universe_10E,\n    poverty_moe_10 = moe_prop(\n      poor_10E,\n      universe_10E,\n      poor_10M,\n      universe_10M\n    ),\n    poverty_se_10 = poverty_moe_10 / 1.645,\n    poverty_cv_10 = poverty_se_10 / poverty_rate_10 * 100,\n\n    poverty_rate_17 = poor_17E / universe_17E,\n    poverty_moe_17 = moe_prop(\n      poor_17E,\n      universe_17E,\n      poor_17M,\n      universe_17M\n    ),\n    poverty_se_17 = poverty_moe_17 / 1.645,\n    poverty_cv_17 = poverty_se_17 / poverty_rate_17 * 100,\n\n    reliability_17 = case_when(\n      is.na(poverty_cv_17) ~ NA_character_,\n      poverty_cv_17 < 12  ~ \"Reliable\",\n      poverty_cv_17 <= 40 ~ \"Somewhat reliable\",\n      TRUE                ~ \"Unreliable\"\n    )\n  )\n\npoverty %>%\n  summarize(\n    n_tracts = n(),\n    missing_2010_rate = sum(is.na(poverty_rate_10)),\n    missing_2017_rate = sum(is.na(poverty_rate_17))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  n_tracts missing_2010_rate missing_2017_rate\n     <int>             <int>             <int>\n1      384                 7                 8\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty %>%\n  filter(\n    is.na(poverty_rate_10) | is.na(poverty_rate_17)\n  ) %>%\n  select(\n    GEOID,\n    NAME,\n    poor_10E,\n    universe_10E,\n    poor_17E,\n    universe_17E\n  ) %>%\n  print(n = Inf, width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 6\n  GEOID       NAME                                                 poor_10E\n  <chr>       <chr>                                                   <dbl>\n1 42101005000 Census Tract 50, Philadelphia County, Pennsylvania          0\n2 42101980300 Census Tract 9803, Philadelphia County, Pennsylvania        0\n3 42101980400 Census Tract 9804, Philadelphia County, Pennsylvania        0\n4 42101980500 Census Tract 9805, Philadelphia County, Pennsylvania        0\n5 42101980600 Census Tract 9806, Philadelphia County, Pennsylvania        9\n6 42101980700 Census Tract 9807, Philadelphia County, Pennsylvania        0\n7 42101980800 Census Tract 9808, Philadelphia County, Pennsylvania        0\n8 42101980900 Census Tract 9809, Philadelphia County, Pennsylvania        0\n  universe_10E poor_17E universe_17E\n         <dbl>    <dbl>        <dbl>\n1            0        0            0\n2            0        0            0\n3            0        0            0\n4            0        0            0\n5           92        0            0\n6            0        0            0\n7            0        0            0\n8            0        0            0\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_compare <- poverty %>%\n  filter(\n    universe_10E > 0,\n    universe_17E > 0\n  )\n\nnrow(poverty_compare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 376\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_compare <- poverty_compare %>%\n  mutate(\n    change_pp = (poverty_rate_17 - poverty_rate_10) * 100,\n    change_moe_pp = sqrt(\n      poverty_moe_10^2 + poverty_moe_17^2\n    ) * 100,\n    lower = change_pp - change_moe_pp,\n    upper = change_pp + change_moe_pp,\n    change_result = case_when(\n      is.na(lower) | is.na(upper) ~ \"Cannot test\",\n      lower > 0 ~ \"Detectable increase\",\n      upper < 0 ~ \"Detectable decrease\",\n      TRUE ~ \"No detectable change\"\n    )\n  )\n\npoverty_compare %>%\n  count(change_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  change_result            n\n  <chr>                <int>\n1 Detectable decrease     27\n2 Detectable increase     36\n3 No detectable change   313\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_compare <- poverty_compare %>%\n  mutate(\n    reliability_10 = case_when(\n      is.na(poverty_cv_10) ~ \"Cannot assess\",\n      poverty_cv_10 < 12 ~ \"Reliable\",\n      poverty_cv_10 <= 40 ~ \"Somewhat reliable\",\n      TRUE ~ \"Unreliable\"\n    ),\n    reliability_17 = case_when(\n      is.na(poverty_cv_17) ~ \"Cannot assess\",\n      poverty_cv_17 < 12 ~ \"Reliable\",\n      poverty_cv_17 <= 40 ~ \"Somewhat reliable\",\n      TRUE ~ \"Unreliable\"\n    )\n  )\n\npoverty_compare %>%\n  count(reliability_10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_10        n\n  <chr>             <int>\n1 Reliable             11\n2 Somewhat reliable   321\n3 Unreliable           44\n```\n\n\n:::\n\n```{.r .cell-code}\npoverty_compare %>%\n  count(reliability_17)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_17        n\n  <chr>             <int>\n1 Reliable             22\n2 Somewhat reliable   332\n3 Unreliable           22\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreliability_counts_10 <- poverty_compare %>%\n  count(reliability_10) %>%\n  rename(\n    reliability = reliability_10,\n    tracts_2010 = n\n  )\n\nreliability_counts_17 <- poverty_compare %>%\n  count(reliability_17) %>%\n  rename(\n    reliability = reliability_17,\n    tracts_2017 = n\n  )\n\nreliability_table <- reliability_counts_10 %>%\n  left_join(reliability_counts_17, by = \"reliability\") %>%\n  mutate(\n    symbol = case_when(\n      reliability == \"Reliable\" ~ \"✓\",\n      reliability == \"Somewhat reliable\" ~ \"~\",\n      reliability == \"Unreliable\" ~ \"!\"\n    )\n  ) %>%\n  select(symbol, reliability, tracts_2010, tracts_2017)\n\nreliability_table %>%\n  gt() %>%\n  tab_header(\n    title = \"Reliability of Philadelphia Tract Poverty Rates\",\n    subtitle = \"376 tracts included in the change comparison\"\n  ) %>%\n  cols_label(\n    symbol = \"Symbol\",\n    reliability = \"CV category\",\n    tracts_2010 = \"2006–2010\",\n    tracts_2017 = \"2013–2017\"\n  ) %>%\n  tab_source_note(\n    source_note = \"Source: ACS 5-year estimates, table B17001. Jurjevich et al. (2018) thresholds: ✓ Reliable, CV < 12%; ~ Somewhat reliable, CV 12–40%; ! Unreliable, CV > 40%.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uwdlwwzgwb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uwdlwwzgwb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uwdlwwzgwb thead, #uwdlwwzgwb tbody, #uwdlwwzgwb tfoot, #uwdlwwzgwb tr, #uwdlwwzgwb td, #uwdlwwzgwb th {\n  border-style: none;\n}\n\n#uwdlwwzgwb p {\n  margin: 0;\n  padding: 0;\n}\n\n#uwdlwwzgwb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uwdlwwzgwb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uwdlwwzgwb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uwdlwwzgwb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uwdlwwzgwb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uwdlwwzgwb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uwdlwwzgwb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uwdlwwzgwb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uwdlwwzgwb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uwdlwwzgwb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uwdlwwzgwb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uwdlwwzgwb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uwdlwwzgwb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uwdlwwzgwb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uwdlwwzgwb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwdlwwzgwb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uwdlwwzgwb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uwdlwwzgwb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uwdlwwzgwb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwdlwwzgwb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uwdlwwzgwb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwdlwwzgwb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uwdlwwzgwb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwdlwwzgwb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uwdlwwzgwb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwdlwwzgwb .gt_left {\n  text-align: left;\n}\n\n#uwdlwwzgwb .gt_center {\n  text-align: center;\n}\n\n#uwdlwwzgwb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uwdlwwzgwb .gt_font_normal {\n  font-weight: normal;\n}\n\n#uwdlwwzgwb .gt_font_bold {\n  font-weight: bold;\n}\n\n#uwdlwwzgwb .gt_font_italic {\n  font-style: italic;\n}\n\n#uwdlwwzgwb .gt_super {\n  font-size: 65%;\n}\n\n#uwdlwwzgwb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uwdlwwzgwb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uwdlwwzgwb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uwdlwwzgwb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uwdlwwzgwb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uwdlwwzgwb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uwdlwwzgwb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uwdlwwzgwb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uwdlwwzgwb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Reliability of Philadelphia Tract Poverty Rates</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>376 tracts included in the change comparison</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"symbol\">Symbol</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"reliability\">CV category</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tracts_2010\">2006–2010</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tracts_2017\">2013–2017</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"symbol\" class=\"gt_row gt_left\">✓</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td>\n<td headers=\"tracts_2010\" class=\"gt_row gt_right\">11</td>\n<td headers=\"tracts_2017\" class=\"gt_row gt_right\">22</td></tr>\n    <tr><td headers=\"symbol\" class=\"gt_row gt_left\">~</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td>\n<td headers=\"tracts_2010\" class=\"gt_row gt_right\">321</td>\n<td headers=\"tracts_2017\" class=\"gt_row gt_right\">332</td></tr>\n    <tr><td headers=\"symbol\" class=\"gt_row gt_left\">!</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td>\n<td headers=\"tracts_2010\" class=\"gt_row gt_right\">44</td>\n<td headers=\"tracts_2017\" class=\"gt_row gt_right\">22</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\">Source: ACS 5-year estimates, table B17001. Jurjevich et al. (2018) thresholds: ✓ Reliable, CV &lt; 12%; ~ Somewhat reliable, CV 12–40%; ! Unreliable, CV &gt; 40%.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlargest_increases <- poverty_compare %>%\n  arrange(desc(change_pp)) %>%\n  head(10)\n\nlargest_decreases <- poverty_compare %>%\n  arrange(change_pp) %>%\n  head(10)\n\nplot_tracts <- bind_rows(largest_increases, largest_decreases)\n\nggplot(\n  plot_tracts,\n  aes(x = reorder(GEOID, change_pp), y = change_pp)\n) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_errorbar(\n    aes(ymin = lower, ymax = upper),\n    width = 0.2\n  ) +\n  geom_point(aes(color = change_result), size = 2.5) +\n  coord_flip() +\n  labs(\n    title = \"Largest Estimated Changes in Philadelphia Tract Poverty\",\n    subtitle = \"2006–2010 to 2013–2017: 10 largest increases and 10 largest decreases\",\n    x = \"Census tract GEOID\",\n    y = \"Change in poverty rate (percentage points)\",\n    color = \"90% confidence test\",\n    caption = \"Source: ACS 5-year estimates, B17001. Bars show 90% confidence intervals for change.\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/change-error-bars-1.png){width=864}\n:::\n:::\n\nThis figure shows the ten largest estimated increases and ten largest estimated\ndecreases, rather than all 376 tracts. Error bars that cross zero indicate changes\nthat are not statistically detectable at 90% confidence.\n\nTract 9891 illustrates the importance of uncertainty. Its estimated poverty rate\nincreased by 23.3 percentage points, but the change's margin of error is about\n221 percentage points. Its poverty-status population estimates were only 68 and\n53, with margins of error larger than those estimates. The resulting approximate\ninterval extends beyond possible changes, indicating that this comparison is too\nimprecise to support a conclusion about the direction of change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchange_counts <- poverty_compare %>%\n  count(change_result)\n\nggplot(\n  change_counts,\n  aes(x = change_result, y = n)\n) +\n  geom_col(fill = \"steelblue\") +\n  geom_text(aes(label = n), vjust = -0.5) +\n  labs(\n    title = \"Most Philadelphia Tracts Had No Detectable Poverty-Rate Change\",\n    subtitle = \"2006–2010 compared with 2013–2017, using 90% confidence\",\n    x = NULL,\n    y = \"Number of census tracts\",\n    caption = \"Source: ACS 5-year estimates, B17001. Includes 376 tracts with defined rates in both periods.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/change-summary-chart-1.png){width=768}\n:::\n:::\n\n### What the results show\n\nOf the 376 tracts included in the comparison, 36 showed a statistically detectable\nincrease in poverty and 27 showed a detectable decrease at 90% confidence.\nThe remaining 313 tracts, or 83.2%, showed no statistically detectable change.\nThis does not mean their poverty rates stayed exactly the same. It means the\nestimated changes were not large enough relative to their uncertainty to\ndistinguish them from zero.\n\nThe reliability table also shows that most tract poverty rates were only\nsomewhat reliable. In 2006–2010, 11 tracts were classified as reliable, 321 as\nsomewhat reliable, and 44 as unreliable. In 2013–2017, those counts were 22,\n332, and 22. These categories describe the precision of each period's poverty\nrate; they do not directly determine whether the change between periods is\nstatistically detectable.\n\nOverall, the results show increases in some tracts and decreases in others.\nThey do not establish what happened in the specific neighborhoods named in the\narticle, because the article's neighborhood-to-tract definitions are unavailable.\nThe tract counts also do not measure the change in Philadelphia's overall poverty\nrate, since tracts contain different numbers of people.\n\n## Part 3: Which Claims Does the Evidence Support?\n\n**Supported:** The article reports that poverty increased in some parts of\nPhiladelphia. My tract-level analysis supports that broad pattern: 36 tracts\nshowed statistically detectable increases between 2006–2010 and 2013–2017.\nHowever, 27 tracts showed detectable decreases, so the direction of change\nvaried across the city. **Not supported by this analysis:** Treating every\nestimated increase as clear evidence that conditions worsened would overstate\nthe findings. For example, Tract 9891 had an estimated increase of 23.3 percentage\npoints, but its extremely large margin of error prevents a confident conclusion\nabout the direction of change. Across all 376 comparable tracts, 313 changes\nwere not statistically distinguishable from zero. This does not prove that\npoverty was unchanged in those places.\n\n**Cannot be determined:** I cannot verify the article's claim that Eastwick's\npoverty rate rose from 12% to 26%, or that it had the largest neighborhood\nincrease, because the article does not identify the tracts used to define each\nneighborhood. The same limitation prevents verification of Fairhill's reported\n61% poverty rate. My analysis also does not test the article's claim about\nincreasing poverty among white residents: the variables used here describe\npoverty across the full poverty-status population, not a specific racial group.\nFinally, these comparisons cannot establish the suggested causes of change,\nsuch as opioid use or migration. Those explanations would require additional\nevidence.\n\n## Part 4: A More Defensible Account\n\nPhiladelphia's poverty trends varied across census tracts between the\n2006–2010 and 2013–2017 American Community Survey periods. Among 376 tracts\nwith usable poverty rates in both periods, 36 showed increases and 27 showed\ndecreases that were statistically detectable at 90% confidence. For the other\n313, uncertainty was too large to establish a change. These results indicate\nworsening poverty in some areas and improvement in others, rather than a\nuniform trend. They also show why a large estimated increase should not\nautomatically be treated as a clear deterioration. The article's exact figures\nfor neighborhoods such as Eastwick and Fairhill cannot be verified through this\ntract-level analysis without knowing how the neighborhood boundaries were\ndefined.\n\n\n\n\n\n\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}